apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simplewebapp 
    env: production
  name: simplewebapp-production
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: simplewebapp
        env: production
    spec:
      containers:
      - image: quay.io/chris_ricci/simplewebapp:v21
        imagePullPolicy: IfNotPresent
        name: simplewebapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
